import { formatDateTimeValue, formatDateValue } from 'src/utils/dateFormat';

export const LINKEDIN_CSV_HEADERS = [
  'ID',
  'Title',
  'Country',
  'Email',
  'Email password',
  'Email recovery email',
  'Email secured',
  'Recovery email',
  'Recovery email password',
  'Recovery email recovery',
  'LinkedIn email',
  'LinkedIn password',
  'LinkedIn link',
  'Second email',
  'LinkedIn secured',
  'Browser',
  'Profile no',
  'Provider',
  'Order ID',
  'Proxy info',
  'Proxy expired by',
  'Purchased from',
  'Renting to',
  'Renting by',
  'Status',
  'Need action',
  'Logs',
  'Created at',
  'Updated at'
];

export function buildLinkedInExportRows(rows) {
  return rows.map((row) => [
    row.id ?? '',
    row.title || '',
    row.country || 'United States',
    row.email || '',
    row.email_password || '',
    row.email_recovery_email || '',
    row.email_secured ? 'true' : 'false',
    row.recovery_email || '',
    row.recovery_email_password || '',
    row.recovery_email_recovery || '',
    row.linkedin_email || '',
    row.linkedin_password || '',
    row.linkedin_link || '',
    row.second_email || '',
    row.linkedin_secured ? 'true' : 'false',
    row.browser || '',
    row.profile_no ?? '',
    row.provider || '',
    row.order_id || '',
    row.proxy_info || '',
    formatDateValue(row.proxy_expired_by),
    row.purchased_from || '',
    row.renting_to || '',
    formatDateValue(row.renting_by),
    row.status || 'Pending',
    row.need_action || 'None',
    row.logs || '',
    formatDateTimeValue(row.created_at),
    formatDateTimeValue(row.updated_at)
  ]);
}
